'use client';

// AI explain-this-line popover.
//
// Plain English: estimator clicks the ❓ button on a row, we ask
// Anthropic to explain in 3-4 bullets what the line covers, what
// rolls into the unit price, and what to double-check. Returns
// plain English, no dollar inventions.

import { useEffect, useState } from 'react';

interface Props {
  apiBaseUrl: string;
  estimateId: string;
  itemIndex: number;
  /** Optional hint of the in-progress unit price the estimator is
   *  typing — overrides whatever's persisted so the explanation
   *  reads against the live number. */
  currentUnitCentsHint?: number;
  onClose: () => void;
}

export function ExplainLinePopover({
  apiBaseUrl,
  estimateId,
  itemIndex,
  currentUnitCentsHint,
  onClose,
}: Props) {
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setError(null);
      try {
        const res = await fetch(
          `${apiBaseUrl}/api/priced-estimates/${encodeURIComponent(estimateId)}/items/${itemIndex}/explain`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(
              currentUnitCentsHint != null ? { currentUnitCentsHint } : {},
            ),
          },
        );
        if (!res.ok) {
          const body = (await res.json().catch(() => ({}))) as {
            error?: string;
          };
          throw new Error(body.error ?? `HTTP ${res.status}`);
        }
        const json = (await res.json()) as { explanation: string };
        if (!cancelled) setText(json.explanation);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Explain failed');
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [apiBaseUrl, estimateId, itemIndex, currentUnitCentsHint]);

  return (
    <div className="absolute right-0 top-full z-30 mt-1 w-80 rounded-md border border-gray-300 bg-white shadow-xl">
      <header className="flex items-center justify-between border-b border-gray-200 px-3 py-2">
        <div className="text-xs font-semibold text-gray-900">
          What this line covers
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-xs text-gray-500 hover:text-gray-900"
        >
          ✕
        </button>
      </header>
      <div className="max-h-80 overflow-y-auto px-3 py-3 text-xs leading-relaxed text-gray-700">
        {text === null && !error && (
          <div className="italic text-gray-400">Asking the model…</div>
        )}
        {error && <div className="text-red-700">⚠ {error}</div>}
        {text && (
          <div className="whitespace-pre-wrap">{text}</div>
        )}
      </div>
      <footer className="border-t border-gray-100 px-3 py-1.5 text-[10px] text-gray-400">
        Generated by AI · double-check anything that affects price.
      </footer>
    </div>
  );
}
